package com.fusesource.demo.wsdl.customerservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2013-09-27T15:20:25.567+10:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */
@WebService(targetNamespace = "http://demo.fusesource.com/wsdl/CustomerService/", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class, com.fusesource.demo.customer.ObjectFactory.class})
public interface CustomerService {

    @RequestWrapper(localName = "getCustomerStatus", targetNamespace = "http://demo.fusesource.com/wsdl/CustomerService/", className = "com.fusesource.demo.wsdl.customerservice.GetCustomerStatus")
    @WebMethod(action = "http://www.example.org/CustomerService/getCustomerStatus")
    @ResponseWrapper(localName = "getCustomerStatusResponse", targetNamespace = "http://demo.fusesource.com/wsdl/CustomerService/", className = "com.fusesource.demo.wsdl.customerservice.GetCustomerStatusResponse")
    public void getCustomerStatus(
        @WebParam(name = "customerId", targetNamespace = "")
        java.lang.String customerId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "statusMessage", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> statusMessage
    );

    @WebResult(name = "ret", targetNamespace = "")
    @RequestWrapper(localName = "lookupCustomer", targetNamespace = "http://demo.fusesource.com/wsdl/CustomerService/", className = "com.fusesource.demo.wsdl.customerservice.LookupCustomer")
    @WebMethod(action = "http://www.example.org/CustomerService/lookupCustomer")
    @ResponseWrapper(localName = "lookupCustomerResponse", targetNamespace = "http://demo.fusesource.com/wsdl/CustomerService/", className = "com.fusesource.demo.wsdl.customerservice.LookupCustomerResponse")
    public com.fusesource.demo.customer.Customer lookupCustomer(
        @WebParam(name = "customerId", targetNamespace = "")
        java.lang.String customerId
    );

    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://demo.fusesource.com/wsdl/CustomerService/", className = "com.fusesource.demo.wsdl.customerservice.UpdateCustomer")
    @WebMethod(action = "http://www.example.org/CustomerService/updateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://demo.fusesource.com/wsdl/CustomerService/", className = "com.fusesource.demo.wsdl.customerservice.UpdateCustomerResponse")
    public void updateCustomer(
        @WebParam(name = "cust", targetNamespace = "")
        com.fusesource.demo.customer.Customer cust
    );
}
