package fr.dcns.myn.scf.gatewaysysext.vms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0.fuse-71-047
 * 2013-09-30T11:26:31.599+10:00
 * Generated source version: 2.6.0.fuse-71-047
 * 
 */
@WebService(targetNamespace = "http://vms.gatewaySysExt.scf.myn.dcns.fr/", name = "VmsRequestWsPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface VmsRequestWsPortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submit", targetNamespace = "http://vms.gatewaySysExt.scf.myn.dcns.fr/", className = "fr.dcns.myn.scf.gatewaysysext.vms.Submit")
    @WebMethod
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://vms.gatewaySysExt.scf.myn.dcns.fr/", className = "fr.dcns.myn.scf.gatewaysysext.vms.SubmitResponse")
    public fr.dcns.myn.scf.gatewaysysext.vms.MessageRetour submit(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<fr.dcns.myn.scf.gatewaysysext.vms.VmsPos> arg0
    );
}
