package com.fusesource.demo.wsdl.customerservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2013-09-27T15:42:48.508+10:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */
@WebServiceClient(name = "CustomerService", 
                  wsdlLocation = "file:/home/jshepher/git-casework/redhat/fuse/spring-cxf-httpprop/ws-gen/src/main/resources/CustomerService.wsdl",
                  targetNamespace = "http://demo.fusesource.com/wsdl/CustomerService/") 
public class CustomerService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.fusesource.com/wsdl/CustomerService/", "CustomerService");
    public final static QName SOAPOverHTTP = new QName("http://demo.fusesource.com/wsdl/CustomerService/", "SOAPOverHTTP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/jshepher/git-casework/redhat/fuse/spring-cxf-httpprop/ws-gen/src/main/resources/CustomerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/jshepher/git-casework/redhat/fuse/spring-cxf-httpprop/ws-gen/src/main/resources/CustomerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "SOAPOverHTTP")
    public CustomerService getSOAPOverHTTP() {
        return super.getPort(SOAPOverHTTP, CustomerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "SOAPOverHTTP")
    public CustomerService getSOAPOverHTTP(WebServiceFeature... features) {
        return super.getPort(SOAPOverHTTP, CustomerService.class, features);
    }

}
