package com.redhat.gss.example.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2012-11-23T13:12:17.713+10:00
 * Generated source version: 2.4.6-redhat-1
 * 
 */
@WebService(targetNamespace = "http://webservices.example.gss.redhat.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservices.example.gss.redhat.com/", className = "com.redhat.gss.example.webservices.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservices.example.gss.redhat.com/", className = "com.redhat.gss.example.webservices.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
