package com.redhat.gss.wss;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2012-11-30T10:32:53.870+10:00
 * Generated source version: 2.4.6-redhat-1
 * 
 */
@WebServiceClient(name = "SecureServiceService", 
                  wsdlLocation = "file:/home/jshepher/git-casework/redhat/wsse-usernametoken/server/src/main/webapp/WEB-INF/wsdl/secureService.wsdl",
                  targetNamespace = "http://wss.gss.redhat.com/") 
public class SecureServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wss.gss.redhat.com/", "SecureServiceService");
    public final static QName SecureServicePort = new QName("http://wss.gss.redhat.com/", "SecureServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/jshepher/git-casework/redhat/wsse-usernametoken/server/src/main/webapp/WEB-INF/wsdl/secureService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SecureServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/jshepher/git-casework/redhat/wsse-usernametoken/server/src/main/webapp/WEB-INF/wsdl/secureService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SecureServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SecureServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecureServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecureServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecureServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecureServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SecureService
     */
    @WebEndpoint(name = "SecureServicePort")
    public SecureService getSecureServicePort() {
        return super.getPort(SecureServicePort, SecureService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecureService
     */
    @WebEndpoint(name = "SecureServicePort")
    public SecureService getSecureServicePort(WebServiceFeature... features) {
        return super.getPort(SecureServicePort, SecureService.class, features);
    }

}
