package server.ws.test.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2012-11-23T16:28:07.480+10:00
 * Generated source version: 2.4.6-redhat-1
 * 
 */
@WebService(targetNamespace = "http://com.test.ws.server/", name = "Service")
@XmlSeeAlso({server.ws.test.com.entity.header.ObjectFactory.class, ObjectFactory.class})
public interface Service {

    @WebResult(name = "testObjectResult", targetNamespace = "")
    @RequestWrapper(localName = "serviceMethod", targetNamespace = "http://com.test.ws.server/", className = "server.ws.test.com.ServiceMethod")
    @WebMethod
    @ResponseWrapper(localName = "serviceMethodResponse", targetNamespace = "http://com.test.ws.server/", className = "server.ws.test.com.ServiceMethodResponse")
    public server.ws.test.com.ServiceOutput serviceMethod(
        @WebParam(name = "testObject", targetNamespace = "")
        server.ws.test.com.ServiceInput testObject
    );
}
