package server.ws.test.com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2012-11-23T16:28:07.510+10:00
 * Generated source version: 2.4.6-redhat-1
 * 
 */
@WebServiceClient(name = "ServiceService", 
                  wsdlLocation = "http://localhost:8080/xmlRootElement/ServiceService?wsdl",
                  targetNamespace = "http://com.test.ws.server/") 
public class ServiceService extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com.test.ws.server/", "ServiceService");
    public final static QName ServicePort = new QName("http://com.test.ws.server/", "ServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/jshepher/git-casework/redhat/xmlRootElement/src/main/webapp/WEB-INF/wsdl/TestWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/jshepher/git-casework/redhat/xmlRootElement/src/main/webapp/WEB-INF/wsdl/TestWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public Service getServicePort() {
        return super.getPort(ServicePort, Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public Service getServicePort(WebServiceFeature... features) {
        return super.getPort(ServicePort, Service.class, features);
    }

}
